SELECT A.NOME, T.NOME, E.CIDADE, E.ESTADO
FROM ALUNO A
INNER JOIN TURMA T 
ON A.ID_TURMA = T.IDTURMA
INNER JOIN ENDERECO E 
ON A.IDALUNO = E.ID_ALUNO
GO

SELECT T.NOME, T.ANO_LETIVO, COUNT(A.IDALUNO) AS 'QTD_ALUNO'
FROM TURMA T
INNER JOIN ALUNO A
ON T.IDTURMA = A.ID_TURMA
GROUP BY T.NOME,T.ANO_LETIVO
ORDER BY T.ANO_LETIVO DESC, T.NOME ASC
GO 

SELECT D.NOME AS 'DISCIPLINA' , COUNT(PD.ID_PROFESSOR) AS 'QTD_PROFESSORES'
FROM DISCIPLINA D
INNER JOIN PROFESSOR_DISCIPLINA PD
ON D.IDDISCIPLINA = PD.ID_DISCIPLINA
GROUP BY D.NOME;
GO

SELECT A.NOME AS 'ALUNO', A.EMAIL
FROM ALUNO A
INNER JOIN ENDERECO E 
ON A.IDALUNO = E.ID_ALUNO
INNER JOIN TURMA T 
ON T.IDTURMA = A.ID_TURMA
WHERE E.ESTADO = 'SP'
OR T.NOME = '6º Ano A'
GO
