CREATE TABLE ATZD_EMAIL(
	IDOPERAÇÃO INT PRIMARY KEY IDENTITY,
	ALUNO VARCHAR(30) NOT NULL,
	CPF VARCHAR (15) NOT NULL UNIQUE,
	DATA_NASCIMENTO DATE,
	EMAIL_ANTIGO VARCHAR(30) NOT NULL,
	EMAIL_NOVO VARCHAR(30) NOT NULL,
	USUARIO VARCHAR(50)NOT NULL,
	DATA DATETIME,
	MENSAGEM VARCHAR(100) NOT NULL
)
GO

CREATE TRIGGER TRG_ATUALIZA_EMAIL
ON DBO.ALUNO
FOR UPDATE AS
IF UPDATE(EMAIL)
BEGIN
		DECLARE @IDALUNO INT
		DECLARE @ALUNO VARCHAR(30)
		DECLARE @CPF VARCHAR(11)
		DECLARE @DATA_NASCIMENTO DATE
		DECLARE @EMAIL_ANTIGO VARCHAR(30)
		DECLARE @EMAIL_NOVO VARCHAR(30)
		DECLARE @USUARIO VARCHAR(30)
		DECLARE @DATA DATETIME
		DECLARE @MENSAGEM VARCHAR(100)

		SELECT @IDALUNO = IDALUNO FROM inserted
		SELECT @ALUNO = NOME FROM inserted
		SELECT @CPF = CPF FROM inserted
		SELECT @DATA_NASCIMENTO = DATA_NASCIMENTO FROM inserted
		SELECT @EMAIL_ANTIGO = EMAIL FROM deleted
		SELECT @EMAIL_NOVO = EMAIL FROM inserted
		
		SELECT @USUARIO = SUSER_NAME()
		SELECT @DATA = GETDATE()
		SELECT @MENSAGEM = 'VALOR INSERIDO PELA TRIGGER TRG_ATUALIZA_EMAIL'

		INSERT INTO ATZD_EMAIL
		(ALUNO,CPF,DATA_NASCIMENTO,EMAIL_ANTIGO,EMAIL_NOVO,USUARIO,DATA,MENSAGEM)
		VALUES
		(@ALUNO,@CPF,@DATA_NASCIMENTO,@EMAIL_ANTIGO,@EMAIL_NOVO,@USUARIO,@DATA,@MENSAGEM)

		PRINT 'TRIGGER EXECUTADA COM SUCESSO'
END
GO
